# Generated by Django 4.1.4 on 2022-12-14 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camos_app', '0003_remove_post_intro_post_job_post_location_post_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='agent',
            field=models.CharField(default="なし", max_length=255),
            preserve_default=False,
        ),
    ]
